!io
version: 0
type: xml
param_root: !list
  objects: {}
  lists:
    ConfigRoot: !list
      objects:
        AttackTypeImpulseData: !obj
          ImpulseUseRate: 0.5
          ImpulsePower: 0.0
          LargeAttackRate: 3.0
          BlastOffAttackRateSmall: 1.5
          BlastOffAttackRateLarge: 3.2
          SpecialAttackRate: 10.0
      lists:
        ImpactImpulseInfo01: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ImpulseObj01: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj02: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj03: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj04: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj05: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                PartImpulseData: !obj {IsUseReceiveImpulse: false, IsUseFixedImpulse: false}
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ImpulseObj01: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj02: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj03: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj04: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj05: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                PartImpulseData: !obj {IsUseReceiveImpulse: false, IsUseFixedImpulse: false}
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ImpulseObj01: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj02: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj03: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj04: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj05: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                PartImpulseData: !obj {IsUseReceiveImpulse: false, IsUseFixedImpulse: false}
              lists: {}
        ImpactImpulseInfo02: !list
          objects: {}
          lists:
            PartImpulseInfo01: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ImpulseObj01: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj02: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj03: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj04: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj05: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                PartImpulseData: !obj {IsUseReceiveImpulse: false, IsUseFixedImpulse: false}
              lists: {}
            PartImpulseInfo02: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ImpulseObj01: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj02: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj03: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj04: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj05: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                PartImpulseData: !obj {IsUseReceiveImpulse: false, IsUseFixedImpulse: false}
              lists: {}
            PartImpulseInfo03: !list
              objects:
                ReceiveObj01: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj02: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ReceiveObj03: !obj {TypeName: !str64 '', DivideFlag: false, ImpulseRate: 0.0,
                  DivideRate: 0.0}
                ImpulseObj01: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj02: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj03: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj04: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                ImpulseObj05: !obj
                  AttackVector: !vec3 [0.0, 0.0, 0.0]
                  AttackPoint: !vec3 [0.0, 0.0, 0.0]
                  ImpulsePower: 0.0
                  TypeName: !str64 
                  UseFlag: false
                PartImpulseData: !obj {IsUseReceiveImpulse: false, IsUseFixedImpulse: false}
              lists: {}
